<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GiftDeck</AssemblyName>
    <RootNamespace>GiftDeck</RootNamespace>
    <ApplicationIcon>Assets\giftdeck.ico</ApplicationIcon>
    <Version>0.1.0</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\giftdeck.ico" />
    <EmbeddedResource Include="Overlays\*.html" />
  </ItemGroup>

</Project>
